# Generated by Django 2.0 on 2018-01-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='area',
            field=models.FloatField(default=100, max_length=100),
        ),
    ]
