# Generated by Django 2.0 on 2018-01-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0002_soil_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='soilfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='soil',
        ),
    ]
