# Generated by Django 2.0 on 2018-01-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0003_auto_20180103_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilfield',
            name='name',
        ),
        migrations.AddField(
            model_name='soilfield',
            name='area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
